repos:
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v2.6.2"
    hooks:
      - id: prettier
  - repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
      - id: black
  - repo: https://github.com/editorconfig-checker/editorconfig-checker.python
    rev: "2.7.1"
    hooks:
      - id: editorconfig-checker-system
        alias: ec
